version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
     - 3306:3306

  web:
    build: .
    ports:
     - 80:80
    links:
     - db
    volumes:
     - ./src/:/var/www/html

  search:
    image: elasticsearch:1.5
    ports:
     - 9200:9200
     - 9300:9300

